cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.shop, name='index'),
    path('search/', views.shop, name='search'),
    path('<slug:category_slug>/', views.shop, name='index'),
    path('product_details/<slug:product_slug>/', views.product_details, name='product_details'),

    # path('post/<int:pk>/', views.post_detail, name='post_detail'),
    # path('post/new/', views.post_new, name='post_new'),
    # path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls', namespace='market')),
    path('shop/', include('goods.urls', namespace='shop')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order', views.create_order, name='create_order'),
    path('payment_success', views.payment_success, name='payment_success'),
    path('payment_failed', views.payment_failed, name='payment_failed'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users_cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

orders/models.py
from django.db import models

from goods.models import Products
from users.models import User


class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    name = models.TextField(null=True, blank=True, verbose_name="Имя заказчика")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    post_index = models.CharField(max_length=20, verbose_name="Почтовый индекс", default='')
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    delivery_city = models.TextField(null=True, blank=True, verbose_name="Город доставки")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    #objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/forms.py
import re
from django import forms


class CreateOrderForm(forms.Form):

    name = forms.CharField()
    phone_number = forms.CharField()
    post_index = forms.CharField()
    delivery_address = forms.CharField()
    delivery_city = forms.CharField()

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")
        
        pattern = re.compile(r'^\d{11}$')
        if not pattern.match(data) and (data[0] != 7 or data[0] != 8):
            raise forms.ValidationError("Неверный формат номера")
        
        return data

orders/views.py
from django.forms import ValidationError
from django.shortcuts import redirect, render
from django.db import transaction

from django.urls import reverse
import stripe
from main import settings
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

from cart.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem
from cart.utils import get_user_carts


def create_order(request):
    user_cart = get_user_carts(request)
    total_prica = user_cart.total_price
    session_data = {
                'mode': 'payment',
                'success_url': request.build_absolute_uri(reverse('orders:payment_success')),
                'cancel_url': request.build_absolute_uri(reverse('orders:payment_failed')),
                'line_items': []
            }

    if request.method == 'POST':


        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            name=form.cleaned_data['name'],
                            phone_number=form.cleaned_data['phone_number'],
                            post_index=form.cleaned_data['post_index'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            delivery_city=form.cleaned_data['delivery_city'],
                        )

                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.sell_price()
                            quantity = cart_item.quantity 

                            if product.quantity < quantity:
                                raise ValidationError(f'Недостаточно товара {name} на складе\
                                                      В наличии {product.quantity}')
                            

                            session_data['line_items'].append({
                            'price_data': {
                                'unit_amount': int(price*100),
                                'currency': 'rub',
                                'product_data': {
                                    'name': name
                                },
                            },
                            'quantity': quantity,
                            })
                            

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            #product.quantity -= quantity
                            #product.save()

                        session_data['client_reference_id'] = order.id
                        session = stripe.checkout.Session.create(**session_data)
                        return redirect(session.url, code=303)
                        #cart_items.delete()

                        
                        #return redirect('user:profile')
            except ValidationError as e:
                return redirect('cart:order')
            
    else:
        form = CreateOrderForm()

    context = {
        'form': form,
    }

    return render(request, 'orders/create_order.html', context=context)

def payment_success(request):
    user_cart = get_user_carts(request)
    total_prica = user_cart.total_price
    user = request.user
    cart_items = Cart.objects.filter(user=user)

    for cart_item in cart_items:
        product = cart_item.product
        quantity = cart_item.quantity 

        product.quantity -= quantity
        product.save()

    cart_items.delete()

    return render(request, 'orders/payment_success.html')


def payment_failed(request):
    return render(request, 'orders/payment_failed.html')

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load cart_tags %}

{% block content %}
<style>
    .row-order-info {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
  
}

.col-25 {
  -ms-flex: 25%; /* IE10 */
  flex: 25%;
}

.col-50 {
  -ms-flex: 50%; /* IE10 */
  flex: 50%;
}

.col-75 {
  -ms-flex: 75%; /* IE10 */
  flex: 75%;
}

.col-25,
.col-50,
.col-75 {
  padding: 0 16px;
}

.container-order-infp {
  background-color: #f2f2f2;
  padding: 5px 20px 15px 20px;
  border: 1px solid lightgrey;
  border-radius: 3px;
}

input[type=text] {
  width: 100%;
  margin-bottom: 20px;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

label {
  margin-bottom: 10px;
  display: block;
}

.icon-container {
  margin-bottom: 20px;
  padding: 7px 0;
  font-size: 24px;
}

.btn {
  background-color: #ffc107;
  color: white;
  padding: 12px;
  margin: 10px 0;
  border: none;
  width: 25%;
  border-radius: 3px;
  cursor: pointer;
  font-size: 17px;
}

.btn:hover {
  background-color: #fc5f49;
}

.vertical-center {
  margin: 0;
  position: absolute;
  top: 50%;
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);
}

span.price {
  float: right;
  color: grey;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (and change the direction - make the "cart" column go on top) */
@media (max-width: 800px) {
  .row {
    flex-direction: column-reverse;
  }
  .col-25 {
    margin-bottom: 20px;
  }
}
</style>
<section>
    <div class="container">
    <div class="cs_height_80 cs_height_lg_60"></div>
    <div class="cs_shop_page_heading text-center">
        <h1 class="cs_fs_50 cs_bold" style="text-align: start;">Выбранные товары</h1>
    </div>
    <div class="cs_height_40"></div>
    </div>
</section>
<section>        
    <div>
        <div id="cart-items-container">
            {% include "cart/includes/cart without button.html" %}
        </div>

        <section>
            <div class="container">
            <div class="cs_height_80 cs_height_lg_60"></div>
            <div class="cs_shop_page_heading text-center">
                <h1 class="cs_fs_50 cs_bold" style="text-align: start;">Детали заказа</h1>
            </div>
            <div class="cs_height_40"></div>
            </div>
        </section>

        <div class="row">
        <div>
            <div class="container">
            <form action="{% url 'orders:create_order' %}" method="post">
                {% csrf_token %}
                <div class="row">
                <div class="col-50">
                    <h3>Заказчик</h3>
                    <label for="id_name"><i class="fa fa-user"></i> Полное имя</label>
                    <input type="text" id="id_name" name="name" placeholder="Иванов Иван Иванович"
                      value="{% if form.name.value %}{{ form.name.value}}{% endif %}">
                      {% if form.name.errors %}
                        <p>{{form.name.errors}}</p>
                      {% endif %}
                    <label for="id_phone_number"><i class="fa-solid fa-mobile-screen-button"></i> Номер телефона</label>
                    <input type="text" id="id_phone_number" name="phone_number" placeholder="+70000000000"
                      value="{% if form.phone_number.value %}{{ form.phone_number.value}}{% endif %}">
                      {% if form.phone_number.errors %}
                        <p>{{form.phone_number.errors}}</p>
                      {% endif %}
                    <label for="id_delivery_address"><i class="fa fa-address-card-o"></i> Адрес (в свободной форме)</label>
                    <input type="text" id="id_delivery_address" name="delivery_address" placeholder="ул. Советска, д. 5, кв. 999"
                      value="{% if form.delivery_address.value %}{{ form.delivery_address.value}}{% endif %}">
                      {% if form.delivery_address.errors %}
                        <p>{{form.delivery_address.errors}}</p>
                      {% endif %}
                </div>

                <div class="col-50">
                  <div class="cs_height_58 cs_height_lg_50"></div>
                  <label for="id_delivery_city"><i class="fa fa-institution"></i> Город</label>
                  <input type="text" id="id_delivery_city" name="delivery_city" placeholder="Москва"
                    value="{% if form.delivery_city.value %}{{ form.delivery_city.value}}{% endif %}">
                    {% if form.delivery_city.errors %}
                      <p>{{form.delivery_city.errors}}</p>
                    {% endif %}
                  <label for="id_post_index">Почтовый индекс</label>
                  <input type="text" id="id_post_index" name="post_index" placeholder="000000"
                    value="{% if form.post_index.value %}{{ form.post_index.value}}{% endif %}">
                  {% if form.post_index.errors %}
                    <p>{{form.post_index.errors}}</p>
                  {% endif %}
                  <!--
                    <h3>Оплата</h3>
                    <label for="fname">Принимаемые карты</label>
                    <div class="icon-container">
                    <i class="fa-brands fa-cc-visa" style="color:navy;"></i>
                    <i class="fa-brands fa-cc-amex" style="color:blue;"></i>
                    <i class="fa-brands fa-cc-mastercard" style="color:red;"></i>
                    <i class="fa-brands fa-cc-discover" style="color:orange;"></i>
                    </div>
                    <label for="cname">Владелец карты</label>
                    <input type="text" id="cname" name="cardname" placeholder="Иван Иванов">
                    <label for="ccnum">Номер карты</label>
                    <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
                    <label for="expmonth">Срок действия</label>
                    <input type="text" id="expmonth" name="expmonth" placeholder="MM/YY">
        
                    <div class="row">
                    <div class="col-50">
                        <label for="cvv">CVV</label>
                        <input type="text" id="cvv" name="cvv" placeholder="123">
                    </div>
                    </div> -->
                </div>
        
                </div>
                
                <div class="container" style="display: flex; justify-content: end; align-items: end;">
                    <input type="submit" value="Перейти к оплате" class="btn">
                </div>
                
            </form>
            </div>
        </div>
        </div>

</section>
{% endblock %}

orders/templates/orders/payment_failed.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <style>
        ._failed{ border-bottom: solid 4px red !important; }
        ._failed i{  color:red !important;  }

        ._success {
            box-shadow: 0 15px 25px #00000019;
            padding: 45px;
            width: 100%;
            text-align: center;
            margin: 40px auto;
            border-bottom: solid 4px #28a745;
        }

        ._success i {
            font-size: 55px;
            color: #28a745;
        }

        ._success h2 {
            margin-bottom: 12px;
            font-size: 40px;
            font-weight: 500;
            line-height: 1.2;
            margin-top: 10px;
        }

        ._success p {
            margin-bottom: 0px;
            font-size: 18px;
            color: #495057;
            font-weight: 500;
        }
        .button-59 {
            align-items: center;
            background-color: #fff;
            border: 2px solid #ffc107;
            box-sizing: border-box;
            color: #ffc107;
            cursor: pointer;
            display: inline-flex;
            fill: #ffc107;
            font-family: Inter,sans-serif;
            font-size: 16px;
            font-weight: 600;
            height: 48px;
            justify-content: center;
            letter-spacing: -.8px;
            line-height: 24px;
            min-width: 140px;
            outline: 0;
            padding: 0 17px;
            text-align: center;
            text-decoration: none;
            transition: all .3s;
            user-select: none;
            -webkit-user-select: none;
            touch-action: manipulation;
            }

        .button-59:focus {
            color: #ffc107;
        }

        .button-59:hover {
            border-color: #fc9449;
            color: #fc9449;
            fill: #fc9449;
        }

        .button-59:active {
            border-color: #fc9449;
            color: #fc9449;
            fill: #fc9449;
        }

        @media (min-width: 768px) {
            .button-59 {
                min-width: 170px;
            }
        }
    </style>


    <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="message-box _success _failed">
                    <i class="fa fa-times-circle" aria-hidden="true"></i>
                    <h2> Платёж не прошел </h2>
                    <p>  Попробуйте оплатить еще раз   </p> 

                    <a href="{% url 'shop:index' 'all' %}"><button class="button-59" role="button">Продолжить покупки</button></a> 
            </div> 
        </div> 
    </div> 

    </div> 
  
{% endblock %}

orders/templates/orders/payment_success.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <style>
        ._failed{ border-bottom: solid 4px red !important; }
        ._failed i{  color:red !important;  }

        ._success {
            box-shadow: 0 15px 25px #00000019;
            padding: 45px;
            width: 100%;
            text-align: center;
            margin: 40px auto;
            border-bottom: solid 4px #28a745;
        }

        ._success i {
            font-size: 55px;
            color: #28a745;
        }

        ._success h2 {
            margin-bottom: 12px;
            font-size: 40px;
            font-weight: 500;
            line-height: 1.2;
            margin-top: 10px;
        }

        ._success p {
            margin-bottom: 0px;
            font-size: 18px;
            color: #495057;
            font-weight: 500;
        }
        .button-59 {
            align-items: center;
            background-color: #fff;
            border: 2px solid #ffc107;
            box-sizing: border-box;
            color: #ffc107;
            cursor: pointer;
            display: inline-flex;
            fill: #ffc107;
            font-family: Inter,sans-serif;
            font-size: 16px;
            font-weight: 600;
            height: 48px;
            justify-content: center;
            letter-spacing: -.8px;
            line-height: 24px;
            min-width: 140px;
            outline: 0;
            padding: 0 17px;
            text-align: center;
            text-decoration: none;
            transition: all .3s;
            user-select: none;
            -webkit-user-select: none;
            touch-action: manipulation;
            }

        .button-59:focus {
            color: #ffc107;
        }

        .button-59:hover {
            border-color: #fc9449;
            color: #fc9449;
            fill: #fc9449;
        }

        .button-59:active {
            border-color: #fc9449;
            color: #fc9449;
            fill: #fc9449;
        }

        @media (min-width: 768px) {
            .button-59 {
                min-width: 170px;
            }
        }
        #outer {
            width:100%;
            text-align: center;
        }
        .inner {
            display: inline-block;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="message-box _success">
                    <i class="fa fa-check-circle" aria-hidden="true"></i>
                    <h2> Оплата прошла успешно </h2>
                    <p> Благодарим вас за покупку!<br>
                        Ваш выбор — наше вдохновение.  </p>  
                    <div class="cs_height_20 cs_height_lg_20"></div>
                    <div id="outer">
                        <a href="{% url 'market:index' %}" class="inner"><button class="button-59" role="button">Главная</button></a> 
                        <a href="{% url 'user:profile' %}" class="inner"><button class="button-59" role="button">Профиль</button></a> 
                    </div> 
                    <div class="cs_height_20 cs_height_lg_20"></div>
            </div> 
        </div> 
    </div> 
    <hr>
{% endblock %}