cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

customauth/urls.py
from django.urls import path
from .views import register, login_view, profile_view, resend_verification_email, verify_email
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'customauth'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('profile/', profile_view, name='profile'),
    # path('edit-profile/', edit_profile, name='edit_profile'),
    path('verify-email/<str:token>/', verify_email, name='verify_email'),
    path('resend-verification-email/', resend_verification_email, name='resend_verification_email'),
    path('logout/', auth_views.LogoutView.as_view(next_page='customauth:logout-success'), name='logout'), 
    path('logout-success/', TemplateView.as_view(template_name='customauth/logout.html'), name='logout-success'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls', namespace='market')),
    path('shop/', include('goods.urls', namespace='shop')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customauth/models.py
from datetime import timezone
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser 


from django.contrib.auth.models import AbstractBaseUser , BaseUserManager
from django.db import models

class MyUserManager(BaseUserManager):

    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have a username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email,
            username,
            password=password,
        )
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user


class MyUser (AbstractBaseUser ):
    email = models.EmailField(verbose_name="email address", max_length=255, unique=True)
    username = models.CharField(max_length=150, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_verification_token = models.CharField(max_length=255, blank=True, null=True)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin
    

class UserProfile(models.Model):
    user = models.OneToOneField(MyUser , on_delete=models.CASCADE)  # Changed from username to user
    name = models.CharField(max_length=50, blank=True)
    surname = models.CharField(max_length=50, blank=True)
    username = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=255, blank=True)  # Use EmailField for consistency

    def __str__(self):
        return self.user.email
    

class EmailVerificationToken(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, default=1)
    token = models.CharField(max_length=64, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_used = models.BooleanField(default=False)

    def __str__(self):
        return f'Token for {self.user.email}'
    


    

customauth/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import MyUser, UserProfile

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Повторите пароль", widget=forms.PasswordInput)

    class Meta:
        model = MyUser 
        fields = ["email", "username"]

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Пароли не совпадают")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'surname', 'username', 'email']

    

customauth/views.py
import uuid
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from .models import MyUser, UserProfile
from .forms import UserCreationForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .emails import send_verification_email
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from .models import EmailVerificationToken

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            send_verification_email(user)
            login(request, user)
            return redirect(reverse('market:index'))
    else:
        form = UserCreationForm()
    return render(request, 'customauth/register.html', {'form': form})

def verify_email(request, token):
    verification_token = get_object_or_404(EmailVerificationToken, token=token)

    if verification_token.is_used:
        messages.error(request, 'Этот токен уже был использован.')
        return redirect('market:index')

    # Подтверждение электронной почты
    user = verification_token.user
    user.email_verified = True
    user.save()

    # Пометить токен как использованный
    verification_token.is_used = True
    verification_token.save()

    messages.success(request, 'Ваша электронная почта успешно подтверждена!')
    return redirect('market:index')


def resend_verification_email(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = MyUser .objects.get(email=email)
            if not user.email_verified:
                # Удаляем старый токен, если он существует
                EmailVerificationToken.objects.filter(user=user).delete()
                # Отправляем новый токен
                send_verification_email(user)
                messages.success(request, 'Токен подтверждения был отправлен на вашу электронную почту.')
            else:
                messages.info(request, 'Ваша электронная почта уже подтверждена.')
        except MyUser .DoesNotExist:
            messages.error(request, 'Пользователь с таким адресом электронной почты не найден.')
    
    return redirect('market:index')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('customauth:profile')
    else:
        form = AuthenticationForm()
    return render(request, 'customauth/login.html', {'form': form})


@login_required
def profile_view(request):
    return render(request, 'customauth/profile.html', {'user': request.user})

customauth/templates/customauth/edit_profile.html
{% extends "market/base.html" %}
{% load static %}

{% block content %}
    <div class="align-items-center">
        <h2>Редактировать профиль</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="cs_btn cs_style_1 cs_fs_16 cs_medium">Сохранить изменения</button>
        </form>
        <a href="{% url 'customauth:profile' %}">Назад к профилю</a>
    </div>
{% endblock %}

customauth/templates/customauth/login.html
{% extends "market/base.html" %}
{% load static %}

{% block content %}
    <div class="align-items-center">
        <h2>Вход</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="cs_btn cs_style_1 cs_fs_16 cs_medium">Войти</button>
        </form>
        <p>Нет аккаунта? <a href="{% url 'customauth:register' %}">Зарегистрироваться</a></p>
    </div>
{% endblock %}

customauth/templates/customauth/logout.html
{% extends "market/base.html" %}

{% block content %}
  <div class="logout-message">
    <h2>Вы вышли из системы!</h2>
    <p>Нажмите здесь, чтобы войти снова:</p>
    <a href="{% url 'customauth:login' %}">Войти</a>
  </div>
{% endblock %}

customauth/templates/customauth/profile.html
{% extends "market/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
    {% if user.is_authenticated and not user.email_verified %}
    <div id="email-verification-alert" style="background-color: rgb(124, 9, 9); color: white; padding: 10px; position: fixed; top: 10px; right: 10px; z-index: 1000;">
        Ваша электронная почта не подтверждена. Пожалуйста, подтвердите её!
        <button onclick="closeAlert()" style="margin-left: 10px; background: none; border: none; color: white; cursor: pointer;">×</button>
    </div>
    <script>
        // Закрыть уведомление через 15 секунд
        setTimeout(function() {
            document.getElementById('email-verification-alert').style.display = 'none';
        }, 15000);

        function closeAlert() {
            document.getElementById('email-verification-alert').style.display = 'none';
        }
    </script>
    {% endif %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url 'customauth:profile' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">

                            {% if not user.email_verified %}
                                <form method="POST" action="{% url 'customauth:resend_verification_email' %}">
                                    {% csrf_token %}
                                    <input type="email" name="email" value="{{ user.email }}" required>
                                    <button type="submit">Повторно отправить токен подтверждения</button>
                                </form>
                            {% endif %}

                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ user.name }}"
                                    required>
                                    {% if user.name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{user.name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ user.surname }}"
                                    required>
                                    {% if user.surname.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{user.surname.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ user.username }}"
                                    required>
                                    {% if user.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{user.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ user.email }}"
                                    required>
                                    {% if user.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{user.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="cs_btn cs_style_1 cs_fs_16 cs_medium">Сохранить изменения</button>
                    </form>
                    <form method="post" action="{% url 'customauth:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark">Выйти из учётной записи</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

customauth/templates/customauth/profile1.html
{% extends "market/base.html" %}
{% load static %}

{% block content %}
    {% if user.is_authenticated and not user.email_verified %}
    <div id="email-verification-alert" style="background-color: rgb(124, 9, 9); color: white; padding: 10px; position: fixed; top: 10px; right: 10px; z-index: 1000;">
        Ваша электронная почта не подтверждена. Пожалуйста, подтвердите её!
        <button onclick="closeAlert()" style="margin-left: 10px; background: none; border: none; color: white; cursor: pointer;">×</button>
    </div>
    <script>
        // Закрыть уведомление через 15 секунд
        setTimeout(function() {
            document.getElementById('email-verification-alert').style.display = 'none';
        }, 15000);

        function closeAlert() {
            document.getElementById('email-verification-alert').style.display = 'none';
        }
    </script>
    {% endif %}
    <div class="align-items-center">
        <h2>Профиль пользователя</h2>

        <!-- {% if user.userprofile and user.userprofile.avatar %}
            <div class="profile-avatar">
                <img src="{{ user.userprofile.avatar.url }}" alt="Аватар" class="avatar">
            </div>
        {% else %}
            <p>Аватар не установлен.</p>
        {% endif %} -->

        <!-- <form method="post" action="{% url 'customauth:resend_verification_email' %}">
            {% csrf_token %}
            <input type="hidden" name="email" value="{{ user.email }}">
            <button type="submit" class="cs_btn cs_style_1 cs_fs_16 cs_medium">Отправить токен подтверждения снова</button>
        </form> -->

        {% if not user.email_verified %}
            <form method="POST" action="{% url 'resend_verification_email' %}">
                {% csrf_token %}
                <input type="email" name="email" value="{{ user.email }}" required>
                <button type="submit">Повторно отправить токен подтверждения</button>
            </form>
        {% endif %}

        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Дата рождения:</strong> {{ user.date_of_birth }}</p>

        {% if user.userprofile %}
            <h3>Дополнительная информация</h3>
            <p><strong>Био:</strong> {{ user.userprofile.bio }}</p>
            <p><strong>Адрес доставки:</strong> {{ user.userprofile.location }}</p>
        {% else %}
            <p>Дополнительная информация отсутствует.</p>
        {% endif %}

        <a href="{% url 'customauth:edit_profile' %}">Редактировать профиль</a>

        <form method="post" action="{% url 'customauth:logout' %}">
            {% csrf_token %}
            <button type="submit" class="cs_btn cs_style_1 cs_fs_16 cs_medium">Выйти</button>
        </form>
    </div>
{% endblock %}

customauth/templates/customauth/register.html
{% extends "market/base.html" %}
{% load static %}

{% block content %}
    <div class="align-items-center">
        <h2>Регистрация</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="cs_btn cs_style_1 cs_fs_16 cs_medium">Зарегистрироваться</button>
        </form>
        <p>Уже есть аккаунт? <a href="{% url 'customauth:login' %}">Войти</a></p>
    </div>
{% endblock %}