cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.shop, name='index'),
    path('search/', views.shop, name='search'),
    path('<slug:category_slug>/', views.shop, name='index'),
    path('product_details/<slug:product_slug>/', views.product_details, name='product_details'),

    # path('post/<int:pk>/', views.post_detail, name='post_detail'),
    # path('post/new/', views.post_new, name='post_new'),
    # path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls', namespace='market')),
    path('shop/', include('goods.urls', namespace='shop')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/models.py
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, verbose_name='URL')
    type = models.CharField(max_length=25, unique=False, blank=True, verbose_name='Тип')

    class Meta:
        verbose_name: 'Категорию'
        verbose_name_plural: 'Категории'

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.CharField(max_length=400, unique=True, blank=True, null=True, verbose_name='URL изображения')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ManyToManyField(to=Categories, verbose_name='Категория')
    size = models.CharField(max_length=1, blank=True, null=True, verbose_name='Размер')
    country = models.CharField(max_length=150, verbose_name='Страна производителя')
    material = models.CharField(max_length=200, verbose_name='Материал')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ("id",)

    def __str__(self):
        return self.name
    
    def sell_price(self):
        return self.price

goods/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404

from goods.models import Products, Categories
from goods.utils import q_search

def shop(request, category_slug=None) -> any:

    page = request.GET.get('page', 1)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if category_slug == "all":
        goods = Products.objects.all()
        category = Categories.objects.get(slug=category_slug).name
    elif query:
        goods = q_search(query)
        category = "Поиск товаров по запросу " + "\"" + query + "\""
    else:
        goods = Products.objects.filter(category__slug=category_slug)
        category = Categories.objects.get(slug=category_slug).name

    if order_by and order_by != "default":
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 16)
    current_page = paginator.page(int(page))

    context = {
        'goods': current_page,
        'slug_url': category_slug,
        'category': category,
    }
    return render(request, 'goods/shop.html', context)

def product_details(request, product_slug) -> any:

    product = Products.objects.get(slug=product_slug)

    context = {
        'product': product,
        'slug_url': product_slug
    }

    return render(request, 'goods/product_details.html', context=context)

goods/templates/goods/product_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Start single product -->
  <section>
    <div class="cs_height_35 cs_height_lg_35"></div>
    <div class="container">
      <!--
      <nav aria-label="breadcrumb">
        <ol class="cs_single_product_breadcrumb breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'market:index' %}">Главная</a></li>
          <li class="breadcrumb-item"><a href="{% url 'shop:index' slug_url %}">Каталог</a></li>
          <li class="breadcrumb-item"><a href="#">{{slug_url}}</a></li>
          <li class="breadcrumb-item active">{{ product.name }}</li>
        </ol>
      </nav>-->
      <div class="row">
        <div class="col-xl-7">
          <div class="row">
            <div class="col-9">
              <div class="cs_single_product_thumb slick-slider">
                <div class="cs_single_product_thumb_item">
                  <img src="{{ product.image }}" alt="Товар">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-5">
          <div class="cs_single_product_details">
            <h2 class="cs_fs_37 cs_semibold">{{ product.name }}</h2>
            <div class="cs_single_product_review">
              <!--<div class="cs_rating_container">
                <div class="cs_rating cs_size_sm" data-rating="5">
                  <div class="cs_rating_percentage"></div>
                </div>
              </div>
              <span>(5)</span>-->
              <span>На складе: <span class="cs_accent_color">{{ product.quantity }}</span></span>
            </div>
            <h4 class="cs_single_product_price cs_fs_21 cs_primary_color cs_semibold">Цена: {{ product.price }}₽</h4>
            <hr>
            <div class="cs_single_product_details_text">
              <p class="mb-0">{{ product.description }}</p>
            </div>
            <div class="cs_single_product_size">
              <h4 class="cs_fs_16 cs_medium">Размер</h4>
              {% if product.size == "Y" %}
              <ul class="cs_size_filter_list cs_mp0">
                <li>
                  <input type="radio" name="size">
                  <span>S</span>
                </li>
                <li>
                  <input type="radio" name="size">
                  <span>M</span>
                </li>
                <li>
                  <input type="radio" name="size">
                  <span>L</span>
                </li>
                <li>
                  <input type="radio" name="size">
                  <span>XL</span>
                </li>
              </ul>
              {% endif %}
            </div>
            <div class="cs_action_btns">
              <div class="cs_quantity">
                <button class="cs_quantity_btn cs_increment"><i class="fa-solid fa-angle-up"></i></button>
                <span class="cs_quantity_input">1</span>
                <button class="cs_quantity_btn cs_decrement"><i class="fa-solid fa-angle-down"></i></button>
              </div>
              <a href="{% url 'cart:cart_add' %}" class="cs_btn cs_style_1 cs_fs_16 cs_medium add-to-cart"
              data-product-id="{{ product.id }}">{% csrf_token %} В корзину</a>
              <!--<button class="cs_heart_btn"><i class="fa-regular fa-heart"></i></button>-->
            </div>
            <ul class="cs_single_product_info">
              <li class="cs_fs_16 cs_normal">
                <b class="cs_medium">Страна производителя: </b>{{ product.country }}
              </li>
              <li class="cs_fs_16 cs_normal">
                <b class="cs_medium">Материал: </b>{{ product.material }}
              </li>
              <li class="cs_fs_16 cs_normal">
                <!--<b class="cs_medium">Категории: {{product.categories}}</b>Levine-->
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="cs_height_70 cs_height_lg_60"></div>
      <hr>
      <!--
      <div class="cs_product_meta_info">
        <ul class="cs_tab_links cs_style_2 cs_product_tab cs_fs_21 cs_primary_color cs_semibold cs_mp0">
          <li><a href="#tab_1">{{ product.description }}</a></li>
          <li><a href="#tab_2">Additional information</a></li>
          <li><a href="#tab_3">Size Guide</a></li>
          <li class="active"><a href="#tab_4">Review (1)</a></li>
        </ul>
        <div class="cs_tabs">
          <div class="cs_tab" id="tab_1">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum
            tincidunt.
            Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
            himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non
            metus.
            Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut
            turpis
            pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec
            erat
            pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.
          </div>
          <div class="cs_tab" id="tab_2">
            <table class="m-0">
              <tbody>
                <tr>
                  <td>Color</td>
                  <td>Blue, Gray, Green, Red, Yellow</td>
                </tr>
                <tr>
                  <td>Size</td>
                  <td>Large, Medium, Small</td>
                </tr>
              </tbody>
            </table>
            <hr>
          </div>
          <div class="cs_tab" id="tab_3">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum
            tincidunt.
            Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
            himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non
            metus.
            Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut
            turpis
            pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec
            erat
            pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.
          </div>
          <div class="cs_tab active" id="tab_4">
            <ul class="cs_client_review_list cs_mp0">
              <li>
                <div class="cs_client_review">
                  <div class="cs_review_media">
                    <div class="cs_review_media_thumb"><img src={{ product.image }} alt="Avatar"></div>
                    <div class="cs_review_media_right">
                      <div class="cs_rating_container">
                        <div class="cs_rating cs_size_sm" data-rating="5">
                          <div class="cs_rating_percentage"></div>
                        </div>
                      </div>
                      <p class="mb-0 cs_primary_color cs_semibold">Zhon Abony</p>
                    </div>
                    <p class="cs_review_posted_by">August 12, 2023</p>
                  </div>
                  <p class="cs_review_text">I recently purchased the Arino T-shirts and I'm thoroughly impressed. The
                    sound quality is exceptional, the wireless connectivity is seamless, and the noise cancellation
                    technology is a <br> standout feature. They're a bit pricey, but well worth the investment. Highly
                    recommend.</p>
                </div>
              </li>
            </ul>
            <p class="m-0">Your email address will not be published. Required fields are marked *</p>
            <div class="cs_height_20 cs_height_lg_20"></div>
            <div class="cs_input_rating_wrap">
              <p>Your rating  *</p>
              <div class="cs_input_rating cs_accent_color" data-rating="0">
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
                <i class="fa-regular fa-star"></i>
              </div>
            </div>
            <div class="cs_height_20 cs_height_lg_22"></div>
            <form class="row cs_review_form cs_gap_y_24">
              <div class="col-lg-12">
                <textarea rows="3" class="cs_form_field" placeholder="Write your review *"></textarea>
              </div>
              <div class="col-lg-6">
                <input type="text" class="cs_form_field" placeholder="Your name *">
              </div>
              <div class="col-lg-6">
                <input type="text" class="cs_form_field" placeholder="Your email *">
              </div>
              <div class="col-lg-12">
                <div class="form_check">
                  <input class="form-check-input" type="checkbox">
                  <label class="form-check-label m-0">
                    By using this form you agree with the storage and handling of your data by this website. *
                  </label>
                </div>
              </div>
              <div class="col-lg-12">
                <button class="cs_btn cs_style_1 cs_fs_16 cs_medium" type="submit">Submit Now</button>
              </div>
            </form>
          </div>
        </div> -->
        <!-- .cs_tabs -->
      </div>
    </div>
  </section>
  <!-- End single product -->
  <hr>
{% endblock %}