cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.shop, name='index'),
    path('search/', views.shop, name='search'),
    path('<slug:category_slug>/', views.shop, name='index'),
    path('product_details/<slug:product_slug>/', views.product_details, name='product_details'),

    # path('post/<int:pk>/', views.post_detail, name='post_detail'),
    # path('post/new/', views.post_new, name='post_new'),
    # path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls', namespace='market')),
    path('shop/', include('goods.urls', namespace='shop')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users_cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

orders/models.py
from django.db import models

from goods.models import Products
from users.models import User


class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    name = models.TextField(null=True, blank=True, verbose_name="Имя заказчика")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    post_index = models.CharField(max_length=20, verbose_name="Почтовый индекс", default='')
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    delivery_city = models.TextField(null=True, blank=True, verbose_name="Город доставки")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    #objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    phone_number = models.CharField(max_length=11, blank=True, null=True)

    class Meta:
        verbose_name: 'Пользователя'
        verbose_name_plural: 'Пользователи'

    def __str__(self):
        return self.username

#g-a223
#absd1234

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

    '''
    username = forms.CharField(
        widget=forms.TextInput(attrs={"autofocus": True,
                                      'style': 'color: #C1C3C6;',
                                      'placeholder': 'Имя пользоватлея',
                                      'class': 'validate',
                                      'autocomplete': 'off'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
                                          'style': 'color: #C1C3C6;',
                                          'placeholder': 'Пароль',
                                          'class': 'validate',
                                          'autocomplete': 'off'}),
    )
    '''


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "username", "password1", "password2",)

    email = forms.CharField()
    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    '''
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "validate",
                "placeholder": "Имя пользователя",
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "validate",
                "placeholder": "E-mail",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "validate",
                "placeholder": "Пароль",
            }
        )
    )
    '''

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css?family=Raleway');
  body {
      margin: 0;
      padding: 0;
      font-family: 'Raleway', sans-serif;
      /*color: #F2F2F2;*/
  }

  #container-login {
      /*background-color: #1D1F20;*/
      position: relative;
      top: 20%;
      margin: auto;
      width: 340px;
      height: 430px;
      border-radius: 0.35em;
      box-shadow: 0 3px 10px 0 rgba(0, 0, 0, 0.2);
      text-align: center;
  }

  #container-register {
      background-color: #1D1F20;
      position: relative;
      top: 20%;
      margin: auto;
      width: 340px;
      height: 480px;
      border-radius: 0.35em;
      box-shadow: 0 3px 10px 0 rgba(0, 0, 0, 0.2);
      text-align: center;
  }

  #title {
      position: relative;
      /*background-color: #1A1C1D;*/
      width: 100%;
      padding: 20px 0px;
      border-radius: 0.35em;
      font-size: 22px;
      border-bottom: 1px solid rgba(255, 255, 255, 0.05);
  }

  .lock {
    position: relative;
    top: 2px;
  }

  .input {
      margin: auto;
      width: 240px;
      border-radius: 4px;
      /*background-color: #373b3d;*/
      padding: 8px 0px;
      margin-top: 15px;
  }

  .input-addon {
      float: left;
      /*background-color: #373b3d;*/
      padding: 10px 10px;
      
  }

  input[type=checkbox] {
      cursor: pointer;
  }

  input[type=text] {
      /*color: #949494;*/
      margin: 0;
      /*background-color: #373b3d;*/
      border: 1px solid #373b3d;
      padding: 6px 0px;
      border-radius: 3px;
  }

  input[type=text]:focus {
      border: 1px solid #373b3d;
  }

  input[type=password] {
      /*color: #949494;*/
      margin: 0;
      /*background-color: #373b3d;*/
      border: 1px solid #373b3d;
      padding: 6px 0px;
      border-radius: 3px;
  }

  input[type=password]:focus {
      border: 1px solid #373b3d;
  }

  input[type=email] {
      /*color: #949494;*/
      margin: 0;
      /*background-color: #373b3d;*/
      border: 1px solid #373b3d;
      padding: 6px 0px;
      border-radius: 3px;
  }

  input[type=email]:focus {
      border: 1px solid #373b3d;
  }

  .forgot-password {
      position: relative;
      bottom: 0%;
  }

  .forgot-password a:link {
      /*color: #C1C3C6;*/
      text-decoration: none;
  }

  .forgot-password a:visited {
      /*color: #C1C3C6;*/
      text-decoration: none;
  }

  .forgot-password a:hover {
      /*color: #FFF;*/
      transition: color 1s;
  }

  .privacy {
      margin-top: 5px;
      position: relative;
      font-size: 12px;
      bottom: 0%;
  }

  .privacy a:link {
      /*color: #949494;*/
      text-decoration: none;
  }

  .privacy a:visited {
      /*color: #949494;*/
      text-decoration: none;
  }

  .privacy a:hover {
      /*color: #C1C3C6;*/
      transition: color 1s;
  }

  *:focus {
      outline: none;
  }

  .remember-me {
      margin: 10px 0;
  }

  input[type=submit] {
      padding: 6px 25px;
      /*background: #373E4A;
      color: #C1C3C6;*/
      font-weight: bold;
      border: 0 none;
      cursor: pointer;
      border-radius: 3px;
      margin-top: 2%;
  }

  input[type=submit]:hover {
      color: #fc5f49;
      transition: color 1s;
  }

  .register {
      margin: auto;
      padding: 16px 0;
      text-align: center;
      margin-top: 5%;
      width: 85%;
      border-top: 1px solid #C1C3C6;
  }

  .clearfix {
      clear: both;
  }

  #register-link {
      margin-top: 10px;
      padding: 6px 25px;
      /*background: #373E4A;
      color: #C1C3C6;*/
      font-weight: bold;
      border: 0 none;
      cursor: pointer;
      border-radius: 3px;
  }
  </style>  

  <div id="container-login">
    <div id="title">
      <i class="fa-solid fa-arrow-right-to-bracket" style="color: #ffcc00;"></i> Вход
    </div>

    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <p>Пожалуйста, введите правильные имя пользователя и пароль</p>
        {% endif %}
        
        <div class="input">
            <div class="input-addon">
              <i for="id_username" class="fa-solid fa-user" style="color: #ffcc00;"></i>
            </div>
            <!--for="{{ form.username.id_for_label }}" {{form.username}}-->
            <input style="color: #C1C3C6;" name="username" id="id_username" placeholder="Имя пользователя" type="text" required class="validate" autocomplete="off">
        </div>

        <div class="clearfix"></div>

        <div class="input">
            <div class="input-addon">
              <i for="id_password" class="fa-solid fa-lock" style="color: #ffcc00;"></i>
            </div>          
            <input style="color: #C1C3C6;" name="password" id="id_password" placeholder="Пароль" type="password" required class="validate" autocomplete="off">
        </div>
        <!--
        <div class="remember-me">
            <input type="checkbox">
            <span style="color: #DDD">Remember Me</span>
        </div>
        -->

        <input type="submit" value="Вход" />
    </form>

    <!--
    <div class="forgot-password">
        <a href="#">Забыли пароль?</a>
    </div>
    -->
    

    <div class="register">
        У вас нет учетной записи?
        <a href="{% url 'user:registration' %}"><button id="register-link">Зарегистрироваться</button></a>
    </div>
  </div>
  <div class="cs_height_140 cs_height_lg_80"></div>
  
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Start Page Heading -->
  <!-- <section class="cs_page_heading text-center position-relative cs_bg_filed" data-src="assets/img/shop_bg.jpg">
    <div class="cs_hero_overlay position-absolute"></div>
    <div class="container position-relative">
      <h2 class="cs_fs_50 cs_bold cs_white_color mb-0">Contact Us</h2>
    </div>
  </section> -->
  <!-- End Page Heading -->
  <!-- Start contact -->
  <section style="margin-left: 5%;" class="container">
    <div id="column1" style="float:left; margin:0; width:13%;">
      <img src="{% static 'img/profile.png' %}" style="margin-top: 80%; ">
    </div>

    <div id="column2" style="float:left; margin:0;width:53%;">
      <div class="cs_height_140 cs_height_lg_80"></div>
      <h3>Имя пользователя: {{user.username}}</h3>
      <h3>Email: {{user.email}}</h3>
      <a href="{% url 'user:logout' %}" class="cs_btn cs_style_1 cs_fs_16 cs_small">Выйти</a>
      <div class="cs_height_80 cs_height_lg_80"></div>
    </div>
    
    <h3>Заказы:</h3>
    <div class="row">
      <div>
        <div class="table-responsive">
          <table class="cs_cart_table">
            <thead>
              <tr>
                <th>Номер заказа</th>
                <th>Дата заказа</th>
                <th>Товар</th>
                <th>Цена</th>
                <th>Количество</th>
                <th>Итого</th>
                <th>Статус</th>
                <th></th>
              </tr>
            </thead>
              {% for order in orders %}
                {% for item in order.orderitem_set.all %}
                  <tbody style="background-color:rgb(235, 235, 235); width:200%">
                    <tr>
                      <td>
                        {{ order.id }}
                      </td>
                      <td>
                        {{ order.created_timestamp}}
                      </td>
                      <td>
                        {{ item.product.name }}
                      </td>
                      <td>
                        {{ item.price }}₽
                      </td>
                      <td>
                        {{ item.quantity }}
                      </td>
                      <td>
                        {{ item.products_price }}₽
                      </td>
                      <td style="color:#fc5f49">
                        {{ order.status }}
                      </td>
                    </tr>
                  </tbody>
                {% endfor %}
              {% endfor %}
          </table>
        </div>
        <div class="cs_height_30 cs_height_lg_30"></div>
      </div>   
    </div>

    <h3>Товары в корзине:</h3>
    <section>
    <!-- Start Cart -->
    
    <div id="cart-items-container">
      {% include "cart/includes/cart.html" %}
    </div>

  </section>
  
  <!-- End contact -->
  <!-- Start instagram
  <div class="cs_instagram">
    <a href="https://www.instagram.com/" target="_blank" class="position-relative cs_instagram_item">
      <div class="cs_instagram_thumb position-relative">
        <img src="assets/img/instagram_1.jpg" alt="Instagram">
      </div>
      <div class="cs_instagram_overlay position-absolute">
        <i class="fa-brands fa-instagram"></i>
      </div>
    </a>
    <a href="https://www.instagram.com/" target="_blank" class="position-relative cs_instagram_item">
      <div class="cs_instagram_thumb position-relative">
        <img src="assets/img/instagram_2.jpg" alt="Instagram">
      </div>
      <div class="cs_instagram_overlay position-absolute">
        <i class="fa-brands fa-instagram"></i>
      </div>
    </a>
    <a href="https://www.instagram.com/" target="_blank" class="position-relative cs_instagram_item">
      <div class="cs_instagram_thumb position-relative">
        <img src="assets/img/instagram_3.jpg" alt="Instagram">
      </div>
      <div class="cs_instagram_overlay position-absolute">
        <i class="fa-brands fa-instagram"></i>
      </div>
    </a>
    <a href="https://www.instagram.com/" target="_blank" class="position-relative cs_instagram_item">
      <div class="cs_instagram_thumb position-relative">
        <img src="assets/img/instagram_4.jpg" alt="Instagram">
      </div>
      <div class="cs_instagram_overlay position-absolute">
        <i class="fa-brands fa-instagram"></i>
      </div>
    </a>
    <a href="https://www.instagram.com/" target="_blank" class="position-relative cs_instagram_item">
      <div class="cs_instagram_thumb position-relative">
        <img src="assets/img/instagram_5.jpg" alt="Instagram">
      </div>
      <div class="cs_instagram_overlay position-absolute">
        <i class="fa-brands fa-instagram"></i>
      </div>
    </a>
    <a href="https://www.instagram.com/" target="_blank" class="position-relative cs_instagram_item">
      <div class="cs_instagram_thumb position-relative">
        <img src="assets/img/instagram_6.jpg" alt="Instagram">
      </div>
      <div class="cs_instagram_overlay position-absolute">
        <i class="fa-brands fa-instagram"></i>
      </div>
    </a>
  </div> -->
  <!-- End instagram -->
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css?family=Raleway');
  body {
      margin: 0;
      padding: 0;
      font-family: 'Raleway', sans-serif;
      /*color: #F2F2F2;*/
  }

  #container-login {
      /*background-color: #1D1F20;*/
      position: relative;
      top: 20%;
      margin: auto;
      width: 340px;
      height: 385px;
      border-radius: 0.35em;
      box-shadow: 0 3px 10px 0 rgba(0, 0, 0, 0.2);
      text-align: center;
  }

  #container-register {
      /*background-color: #1D1F20;*/
      position: relative;
      top: 20%;
      margin: auto;
      width: 340px;
      height: 510px;
      border-radius: 0.35em;
      box-shadow: 0 3px 10px 0 rgba(0, 0, 0, 0.2);
      text-align: center;
  }

  #title {
      position: relative;
      /*background-color: #1A1C1D;*/
      width: 100%;
      padding: 20px 0px;
      border-radius: 0.35em;
      font-size: 22px;
      border-bottom: 1px solid rgba(255, 255, 255, 0.05);
  }

  .lock {
    position: relative;
    top: 2px;
  }

  .input {
      margin: auto;
      width: 240px;
      border-radius: 4px;
      /*background-color: #373b3d;*/
      padding: 8px 0px;
      margin-top: 15px;
  }

  .input-addon {
      float: left;
      /*background-color: #373b3d;*/
      padding: 10px 10px;
      
  }

  input[type=checkbox] {
      cursor: pointer;
  }

  input[type=text] {
      /*color: #949494;*/
      margin: 0;
      /*background-color: #373b3d;*/
      border: 1px solid #373b3d;
      padding: 6px 0px;
      border-radius: 3px;
  }

  input[type=text]:focus {
      border: 1px solid #373b3d;
  }

  input[type=password] {
      /*color: #949494;*/
      margin: 0;
      /*background-color: #373b3d;*/
      border: 1px solid #373b3d;
      padding: 6px 0px;
      border-radius: 3px;
  }

  input[type=password]:focus {
      border: 1px solid #373b3d;
  }

  input[type=email] {
      /*color: #949494;*/
      margin: 0;
      /*background-color: #373b3d;*/
      border: 1px solid #373b3d;
      padding: 6px 0px;
      border-radius: 3px;
  }

  input[type=email]:focus {
      border: 1px solid #373b3d;
  }

  .forgot-password {
      position: relative;
      bottom: 0%;
  }

  .forgot-password a:link {
      /*color: #C1C3C6;*/
      text-decoration: none;
  }

  .forgot-password a:visited {
      /*color: #C1C3C6;*/
      text-decoration: none;
  }

  .forgot-password a:hover {
      /*color: #FFF;*/
      transition: color 1s;
  }

  .privacy {
      margin-top: 5px;
      position: relative;
      font-size: 12px;
      bottom: 0%;
  }

  .privacy a:link {
      /*color: #949494;*/
      text-decoration: none;
  }

  .privacy a:visited {
      /*color: #949494;*/
      text-decoration: none;
  }

  .privacy a:hover {
      /*color: #C1C3C6;*/
      transition: color 1s;
  }

  *:focus {
      outline: none;
  }

  .remember-me {
      margin: 10px 0;
  }

  input[type=submit] {
      padding: 6px 25px;
      /*background: #373E4A;
      color: #C1C3C6;*/
      font-weight: bold;
      border: 0 none;
      cursor: pointer;
      border-radius: 3px;
      margin-top: 2%;
  }

  input[type=submit]:hover {
      color: #fc5f49;
      transition: color 1s;
  }

  .register {
      margin: auto;
      padding: 16px 0;
      text-align: center;
      margin-top: 5%;
      width: 85%;
      border-top: 1px solid #C1C3C6;
  }

  .clearfix {
      clear: both;
  }

  #register-link {
      margin-top: 10px;
      padding: 6px 25px;
      /*background: #373E4A;
      color: #C1C3C6;*/
      font-weight: bold;
      border: 0 none;
      cursor: pointer;
      border-radius: 3px;
  }
  </style>  

  <div id="container-register">
    <div id="title">
      <i class="fa-solid fa-arrow-right-to-bracket" style="color: #ffcc00;"></i> Регистрация
    </div>

    <form action="{% url 'user:registration' %}" method="post">
        {% csrf_token %}      

        <div class="input">
          <div class="input-addon">
            <i for="id_email" class="fa-regular fa-envelope" style="color: #ffcc00;"></i>
          </div>
          <input id="id_email" name="email" placeholder="Email" type="email" 
            required class="validate" autocomplete="off" style="color: #C1C3C6;"
            value="{% if form.email.value %}{{ form.email.value}}{% endif %}">
          {% if form.email.errors %}
          <p>{{form.email.errors}}</p>
          {% endif %}
        </div>

        <div class="clearfix"></div>

        <div class="input">
            <div class="input-addon">
              <i for="id_username" class="fa-solid fa-user" style="color: #ffcc00;"></i>
            </div>
            <input style="color: #C1C3C6;" name="username" id="id_username" placeholder="Имя пользователя" 
                type="text" required class="validate" autocomplete="off"
                value="{% if form.username.value %}{{ form.username.value}}{% endif %}">
            {% if form.username.errors %}
            <p>{{form.username.errors}}</p>
            {% endif %}
        </div>

        <div class="clearfix"></div>

        <div class="input">
            <div class="input-addon">
              <i for="id_password1" class="fa-solid fa-lock" style="color: #ffcc00;"></i>
            </div>
            <input style="color: #C1C3C6;" name="password1" id="id_password1" placeholder="Пароль" 
                type="password" required class="validate" autocomplete="off"
                value="{% if form.password1.value %}{{ form.password1.value}}{% endif %}">
            {% if form.password1.errors %}
            <p>{{form.password1.errors}}</p>
            {% endif %}
        </div>
        <div class="input">
            <div class="input-addon">
              <i for="id_password2" class="fa-solid fa-lock" style="color: #ffcc00;"></i>
            </div>
            <input style="color: #C1C3C6;" name="password2" id="id_password2" placeholder="Пароль еще раз" 
                type="password" required class="validate" autocomplete="off"
                value="{% if form.password2.value %}{{ form.password2.value}}{% endif %}">
            {% if form.password2.errors %}
            <p>{{form.password2.errors}}</p>
            {% endif %}
            </div>

        <!--
        <div class="remember-me">
            <input type="checkbox">
            <span style="color: #DDD">Remember Me</span>
        </div>
        -->

        <input type="submit" value="Регистрация" />
    </form>

    <!--
    <div class="forgot-password">
        <a href="#">Забыли пароль?</a>
    </div>
    -->
    

    <div class="register">
        Уже есть учетная запись?
        <a href="{% url 'user:login' %}"><button id="register-link">Войти</button></a>
    </div>
  </div>
  <div class="cs_height_140 cs_height_lg_80"></div>
  
{% endblock %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Start Cart Page Heading -->
  <section>
    <div class="container">
      <div class="cs_height_80 cs_height_lg_60"></div>
      <div class="cs_shop_page_heading text-center">
        <h1 class="cs_fs_50 cs_bold">Корзина</h1>
        <div class="cs_shop_breadcamp cs_medium">
          <a href="{% url 'market:index' %}">Главная</a>
          <svg width="17" height="8" viewBox="0 0 17 8" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M16.3536 4.35355C16.5488 4.15829 16.5488 3.84171 16.3536 3.64645L13.1716 0.464467C12.9763 0.269205 12.6597 0.269205 12.4645 0.464467C12.2692 0.659729 12.2692 0.976312 12.4645 1.17157L15.2929 4L12.4645 6.82843C12.2692 7.02369 12.2692 7.34027 12.4645 7.53553C12.6597 7.7308 12.9763 7.7308 13.1716 7.53554L16.3536 4.35355ZM-4.37114e-08 4.5L16 4.5L16 3.5L4.37114e-08 3.5L-4.37114e-08 4.5Z" fill="#5E5E5E"/>
          </svg>            
          <span>Корзина</span>
        </div>
      </div>
      <div class="cs_height_80 cs_height_lg_60"></div>
    </div>
  </section>
  <!-- End Cart Page Heading -->
  <!-- Start Cart -->
  <div id="cart-items-container">
    {% include "cart/includes/cart.html" %}
  </div>
  <!-- End Cart -->
  <div class="cs_height_110 cs_height_lg_50"></div>
  <hr>
  
{% endblock %}